import './globals.css'
import { Inter } from 'next/font/google'
import TopBar from '../components/TopBar'
import BottomBar from '@/components/BottomBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '天樹祭 2023',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <TopBar />
        <main>
          {children}
        </main>
        <BottomBar />
      </body>
    </html>
  )
}
